version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: single_stage.Dockerfile
    deploy:
      replicas: 4
    environment:
      - PING_LISTEN_PORT=3000
    expose:
      - '3000'
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 8080:8081
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf
    depends_on:
      - api